services:
    webworks.core.twig_extension:
        class: webworks\CoreBundle\Twig\TwigExtension
        public: false
        arguments: ['@service_container']
        tags:
            - { name: twig.runtime }
